# Generated by Django 5.2.16 on 2026-07-15 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentRequest',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
