# Generated by Django 5.2.16 on 2026-07-15 10:03

import admin_portail.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('type', models.CharField(choices=[('CONTRACT', 'Contrat'), ('ADDENDUM', 'Avenant'), ('OTHER', 'Autre')], default='CONTRACT', max_length=20)),
                ('file_url', models.FileField(upload_to='admin_portail/documents/%Y/%m/', validators=[admin_portail.models.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WORK_CERTIFICATE', 'Attestation de travail'), ('SALARY_CERTIFICATE', 'Attestation de salaire'), ('WORK_CONTRACT_CERT', 'Certificat de travail')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('READY', 'Prêt'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='admin_portail/documents_requests/%Y/%m/', validators=[admin_portail.models.validate_pdf_file])),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de document',
                'verbose_name_plural': 'Demandes de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PAID', 'Congé payé'), ('RTT', 'RTT'), ('UNPAID', 'Sans solde'), ('SICK', 'Maladie')], default='PAID', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_days', models.IntegerField(verbose_name='Jours ouvrables')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(verbose_name='Mois')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('file_url', models.FileField(upload_to='admin_portail/payslips/%Y/%m/', validators=[admin_portail.models.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
