/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "border": "#c5c5d3",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed": "#001f26",
        "inverse-surface": "#213145",
        "tertiary": "#002f38",
        "on-error-container": "#93000a",
        "outline-variant": "#c5c5d3",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#003ea8",
        "on-primary-fixed-variant": "#264191",
        "on-secondary-fixed": "#00174b",
        "surface-container": "#e5eeff",
        "on-primary-fixed": "#00164e",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#90a8ff",
        "on-primary": "#ffffff",
        "outline": "#757682",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "primary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "secondary-fixed": "#dbe1ff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-surface-variant": "#444651",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#acedff",
        "on-tertiary-container": "#1dbcda",
        "secondary-container": "#316bf3",
        "secondary": "#0051d5",
        "surface-tint": "#4059aa",
        "inverse-primary": "#b6c4ff",
        "background": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#1e3a8a",
        "surface-container-highest": "#d3e4fe",
        "tertiary-container": "#004754",
        "on-secondary-container": "#fefcff",
        "surface": "#f8f9ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b6c4ff",
        "primary": "#00236f"
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      }
    },
  },
  plugins: [require("@tailwindcss/forms")],
}