# Generated by Django 6.0.6 on 2026-07-06 10:59

import admin_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_url",
            field=models.FileField(
                upload_to="documents/",
                validators=[admin_portal.models.validate_pdf_file],
            ),
        ),
    ]
