# Generated by Django 6.0.6 on 2026-07-06 11:20

import admin_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0002_alter_document_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="file_url",
            field=models.FileField(
                upload_to="payslips/",
                validators=[admin_portal.models.validate_pdf_file],
            ),
        ),
    ]
