"""
Django settings for rh_project project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path


# --------------------------------------------------
# CHEMINS DU PROJET
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# SÉCURITÉ
# --------------------------------------------------

SECRET_KEY = (
    "django-insecure-xnu^xf5@=@&c7nnn3$z(v9=6wth%(d^!k&)f-t@_t+3@3zpe^7"
)

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# --------------------------------------------------
# APPLICATIONS INSTALLÉES
# --------------------------------------------------

INSTALLED_APPS = [
    # Applications Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Bibliothèques externes
    "rest_framework",
    "corsheaders",

    # Applications du projet
    "accounts",
    "admin_portal",
    "employee",
]


# Modèle utilisateur personnalisé déjà créé par ta collègue
AUTH_USER_MODEL = "accounts.User"


# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS doit être placé avant CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# --------------------------------------------------
# URLS ET TEMPLATES
# --------------------------------------------------

ROOT_URLCONF = "rh_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rh_project.wsgi.application"


# --------------------------------------------------
# BASE DE DONNÉES
# --------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# --------------------------------------------------
# VALIDATION DES MOTS DE PASSE
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# --------------------------------------------------
# LANGUE ET FUSEAU HORAIRE
# --------------------------------------------------

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Casablanca"

USE_I18N = True

USE_TZ = True


# --------------------------------------------------
# FICHIERS STATIQUES
# --------------------------------------------------

STATIC_URL = "/static/"


# --------------------------------------------------
# FICHIERS MÉDIAS
# Photos, documents et bulletins PDF envoyés dans Django
# --------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# --------------------------------------------------
# CONNEXION REACT ↔ DJANGO
# --------------------------------------------------

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
]

CORS_ALLOW_CREDENTIALS = True


# --------------------------------------------------
# DJANGO REST FRAMEWORK
# Pas d'authentification pour ta partie Employee
# --------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
}


# --------------------------------------------------
# TYPE DES IDENTIFIANTS AUTOMATIQUES
# --------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"